feat(conway): add cost model update proposal flow
Make sure we are using up-to-date cost models in Conway Slow testnet.

- Add cost_models_list_185_v2_v3.json with PlutusV1/V2/V3 cost models.
- Implement cost model update proposal and voting before hard fork to PV10.
- Add checks for cost model enactment and protocol version after update.

diff --git a/src/cardonnay_scripts/scripts/conway_slow/start-cluster b/src/cardonnay_scripts/scripts/conway_slow/start-cluster
--- a/src/cardonnay_scripts/scripts/conway_slow/start-cluster
+++ b/src/cardonnay_scripts/scripts/conway_slow/start-cluster
@@ -87,6 +87,7 @@ cp "${SCRIPT_DIR}/submit-api-config.json" "$STATE_CLUSTER"
 cp "${SCRIPT_DIR}/supervisor.conf" "$STATE_CLUSTER"
 cp "$SCRIPT_DIR/testnet.json" "$STATE_CLUSTER"
 cp "$SCRIPT_DIR"/*genesis*.spec.json "${STATE_CLUSTER}/shelley/"
+cp "$SCRIPT_DIR"/cost_models*.json "${STATE_CLUSTER}/shelley/"
 
 if [ -n "${PV9:-""}" ]; then
   cp -f \
@@ -1060,7 +1061,6 @@ if cardano_cli_log latest query protocol-parameters \
   --out-file "${STATE_CLUSTER}/pparams.json"; then
 
   PROTOCOL_VERSION="$(jq ".protocolVersion.major" < "${STATE_CLUSTER}/pparams.json")"
-
   [ "$PROTOCOL_VERSION" = 6 ] || { echo "Unexpected protocol version '$PROTOCOL_VERSION' on line $LINENO" >&2; exit 1; }  # assert
 fi
 
@@ -1166,7 +1166,6 @@ if cardano_cli_log latest query protocol-parameters \
   --out-file "${STATE_CLUSTER}/pparams.json"; then
 
   PROTOCOL_VERSION="$(jq ".protocolVersion.major" < "${STATE_CLUSTER}/pparams.json")"
-
   [ "$PROTOCOL_VERSION" = 8 ] || { echo "Unexpected protocol version '$PROTOCOL_VERSION' on line $LINENO" >&2; exit 1; }  # assert
 fi
 
@@ -1225,7 +1224,6 @@ cardano_cli_log latest query protocol-parameters \
   --out-file "${STATE_CLUSTER}/pparams.json"
 
 PROTOCOL_VERSION="$(jq ".protocolVersion.major" < "${STATE_CLUSTER}/pparams.json")"
-
 [ "$PROTOCOL_VERSION" = 9 ] || { echo "Unexpected protocol version '$PROTOCOL_VERSION' on line $LINENO" >&2; exit 1; }  # assert
 
 # Register CC members, DReps, all in one big transaction:
@@ -1314,12 +1312,119 @@ if [ -z "${NO_CC:-""}" ]; then
     { echo "The CC members were not registered, line $LINENO" >&2; exit 1; }  # assert
 fi
 
-# Hard fork to Conway protocol version 10
+# Hard fork to Conway protocol version 10 + cost model update
 
 if [ -z "${PV9:-""}" ]; then
-  PV10_ACTION="${STATE_CLUSTER}/governance_data/hardfork_pv10_action"
+  # We submit the cost model update first, so we can get it ratified before submitting the
+  # hard fork proposal. After the hard fork proposal is ratified, ratification of other actions
+  # is delayed. That would prolong testnet startup, if we switched the order and ratified the
+  # hard fork first (and we would also need to vote with DReps in post-bootstrap epochs).
+  echo "Submitting cost model update proposal"
+  COST_MODEL_ACTION="${STATE_CLUSTER}/governance_data/cost_model_conway_action"
+
+  cardano_cli_log conway governance action create-protocol-parameters-update \
+    --testnet \
+    --governance-action-deposit "$GOV_ACTION_DEPOSIT" \
+    --deposit-return-stake-verification-key-file "${STATE_CLUSTER}/nodes/node-pool1/reward.vkey" \
+    --anchor-url "http://www.cost-model-update.com" \
+    --anchor-data-hash 5d372dca1a4cc90d7d16d966c48270e33e3aa0abcb0e78f0d5ca7ff330d2245d \
+    --cost-model-file "${STATE_CLUSTER}/shelley/cost_models_list_185_v2_v3.json" \
+    --out-file "${COST_MODEL_ACTION}.action"
+
+  STOP_TXIN_AMOUNT="$((FEE + GOV_ACTION_DEPOSIT))"
+
+  get_txins "$FAUCET_ADDR" "$STOP_TXIN_AMOUNT"
+
+  TXOUT_AMOUNT="$((TXIN_AMOUNT - STOP_TXIN_AMOUNT))"
+
+  cardano_cli_log conway transaction build-raw \
+    --fee    "$FEE" \
+    "${TXINS[@]}" \
+    --proposal-file "${COST_MODEL_ACTION}.action" \
+    --tx-out "${FAUCET_ADDR}+${TXOUT_AMOUNT}" \
+    --out-file "${COST_MODEL_ACTION}-tx.txbody"
+
+  cardano_cli_log conway transaction sign \
+    --signing-key-file "$FAUCET_SKEY" \
+    --testnet-magic    "$NETWORK_MAGIC" \
+    --tx-body-file     "${COST_MODEL_ACTION}-tx.txbody" \
+    --out-file         "${COST_MODEL_ACTION}-tx.tx"
+
+  cardano_cli_log conway transaction submit \
+    --tx-file "${COST_MODEL_ACTION}-tx.tx" \
+    --testnet-magic "$NETWORK_MAGIC"
+
+  sleep "$SUBMIT_DELAY"
+  if ! check_spend_success "${TXINS[@]}"; then
+    echo "Failed to spend Tx inputs, line $LINENO" >&2  # assert
+    exit 1
+  fi
+
+  COST_MODEL_ACTION_TXID="$(cardano_cli_log conway transaction txid \
+    --output-text --tx-body-file "${COST_MODEL_ACTION}-tx.txbody")"
+
+  echo "Voting on cost model update proposal"
+
+  INDEX=0
+  for f in "$STATE_CLUSTER"/governance_data/cc_member*_committee_hot.vkey; do
+    [ -e "$f" ] || continue
+    INDEX="$((INDEX + 1))"
+    cardano_cli_log conway governance vote create \
+      --yes \
+      --governance-action-tx-id "$COST_MODEL_ACTION_TXID" \
+      --governance-action-index 0 \
+      --cc-hot-verification-key-file "$f" \
+      --out-file "${COST_MODEL_ACTION}_cc${INDEX}.vote"
+  done
+
+  # Submit the votes
+
+  COST_MODEL_VOTES="${STATE_CLUSTER}/governance_data/cost_model_conway_votes"
+
+  VOTE_FILES=()
+  for f in "$COST_MODEL_ACTION"_*.vote; do
+    VOTE_FILES+=( "--vote-file" "$f" )
+  done
+
+  CC_SIGNING=()
+  for f in "$STATE_CLUSTER"/governance_data/cc_member*_committee_hot.skey; do
+    [ -e "$f" ] || continue
+    CC_SIGNING+=( "--signing-key-file" "$f" )
+  done
+
+  get_txins "$FAUCET_ADDR" "$FEE"
+
+  TXOUT_AMOUNT="$((TXIN_AMOUNT - FEE))"
+
+  cardano_cli_log conway transaction build-raw \
+    --fee    "$FEE" \
+    "${TXINS[@]}" \
+    "${VOTE_FILES[@]}" \
+    --tx-out "${FAUCET_ADDR}+${TXOUT_AMOUNT}" \
+    --out-file "${COST_MODEL_VOTES}-tx.txbody"
+
+  cardano_cli_log conway transaction sign \
+    --signing-key-file "$FAUCET_SKEY" \
+    "${CC_SIGNING[@]}" \
+    --testnet-magic    "$NETWORK_MAGIC" \
+    --tx-body-file     "${COST_MODEL_VOTES}-tx.txbody" \
+    --out-file         "${COST_MODEL_VOTES}-tx.tx"
+
+  cardano_cli_log conway transaction submit \
+    --tx-file "${COST_MODEL_VOTES}-tx.tx" \
+    --testnet-magic "$NETWORK_MAGIC"
+
+  sleep "$SUBMIT_DELAY"
+  if ! check_spend_success "${TXINS[@]}"; then
+    echo "Failed to spend Tx inputs, line $LINENO" >&2  # assert
+    exit 1
+  fi
+
+  wait_for_epoch "$((CONWAY_PV9_EPOCH + 1))"
 
   echo "Submitting hard fork proposal to update to Conway PV10"
+
+  PV10_ACTION="${STATE_CLUSTER}/governance_data/hardfork_pv10_action"
 
   cardano_cli_log conway governance action create-hardfork \
     --testnet \
@@ -1360,7 +1465,8 @@ if [ -z "${PV9:-""}" ]; then
     exit 1
   fi
 
-  ACTION_TXID="$(cardano_cli_log conway transaction txid --output-text --tx-body-file "${PV10_ACTION}-tx.txbody")"
+  PV10_ACTION_TXID="$(cardano_cli_log conway transaction txid \
+    --output-text --tx-body-file "${PV10_ACTION}-tx.txbody")"
 
   echo "Voting on hard fork proposal"
 
@@ -1370,7 +1476,7 @@ if [ -z "${PV9:-""}" ]; then
     INDEX="$((INDEX + 1))"
     cardano_cli_log conway governance vote create \
       --yes \
-      --governance-action-tx-id "$ACTION_TXID" \
+      --governance-action-tx-id "$PV10_ACTION_TXID" \
       --governance-action-index 0 \
       --cc-hot-verification-key-file "$f" \
       --out-file "${PV10_ACTION}_cc${INDEX}.vote"
@@ -1381,7 +1487,7 @@ if [ -z "${PV9:-""}" ]; then
     INDEX="$((INDEX + 1))"
     cardano_cli_log conway governance vote create \
       --yes \
-      --governance-action-tx-id "$ACTION_TXID" \
+      --governance-action-tx-id "$PV10_ACTION_TXID" \
       --governance-action-index 0 \
       --cold-verification-key-file "$f" \
       --out-file "${PV10_ACTION}_spo${INDEX}.vote"
@@ -1404,9 +1510,7 @@ if [ -z "${PV9:-""}" ]; then
 
   POOL_SIGNING=()
   for f in "$STATE_CLUSTER"/nodes/node-pool*/cold.skey; do
-    POOL_SIGNING+=( \
-      "--signing-key-file" "$f" \
-    )
+    POOL_SIGNING+=( "--signing-key-file" "$f" )
   done
 
   get_txins "$FAUCET_ADDR" "$FEE"
@@ -1438,15 +1542,27 @@ if [ -z "${PV9:-""}" ]; then
     exit 1
   fi
 
-  echo "Waiting for Conway PV10 to start"
+  echo "Waiting for cost model update to get enacted"
   wait_for_epoch "$((CONWAY_PV9_EPOCH + 2))"
 
   cardano_cli_log conway query protocol-parameters \
     --testnet-magic "$NETWORK_MAGIC" \
     --out-file "${STATE_CLUSTER}/pparams.json"
 
-  PROTOCOL_VERSION="$(jq ".protocolVersion.major" < "${STATE_CLUSTER}/pparams.json")"
+  PLUTUSV2_COST_MODEL_LEN="$(jq ".costModels.PlutusV2 | length" < "${STATE_CLUSTER}/pparams.json")"
+  if [ "$PLUTUSV2_COST_MODEL_LEN" != 185 ]; then
+    echo "Unexpected PlutusV2 cost model length '$PLUTUSV2_COST_MODEL_LEN' on line $LINENO" >&2  # assert
+    exit 1
+  fi
 
+  echo "Waiting for Conway PV10 to start"
+  wait_for_epoch "$((CONWAY_PV9_EPOCH + 3))"
+
+  cardano_cli_log conway query protocol-parameters \
+    --testnet-magic "$NETWORK_MAGIC" \
+    --out-file "${STATE_CLUSTER}/pparams.json"
+
+  PROTOCOL_VERSION="$(jq ".protocolVersion.major" < "${STATE_CLUSTER}/pparams.json")"
   [ "$PROTOCOL_VERSION" = 10 ] || { echo "Unexpected protocol version '$PROTOCOL_VERSION' on line $LINENO" >&2; exit 1; }  # assert
 fi
 
