refactor(scripts): use DBSYNC_SCHEMA var and binaries in PATH
Replace usage of DBSYNC_REPO with DBSYNC_SCHEMA to specify the db-sync
schema directory, and update scripts to call cardano-db-sync and
cardano-smash-server from PATH instead of using binaries from a repo
directory. Update environment variable documentation in testnet.json
files accordingly. This simplifies configuration and improves
compatibility with system-installed binaries.

diff --git a/src/cardonnay_scripts/scripts/conway_slow/start-cluster b/src/cardonnay_scripts/scripts/conway_slow/start-cluster
--- a/src/cardonnay_scripts/scripts/conway_slow/start-cluster
+++ b/src/cardonnay_scripts/scripts/conway_slow/start-cluster
@@ -116,9 +116,9 @@ serverurl = unix:///${SUPERVISORD_SOCKET_PATH}
 EoF
 
 # enable db-sync service
-if [ -n "${DBSYNC_REPO:-""}" ]; then
-  [ -e "${DBSYNC_REPO}/db-sync-node/bin/cardano-db-sync" ] || \
-    { echo "The \`${DBSYNC_REPO}/db-sync-node/bin/cardano-db-sync\` not found, line $LINENO" >&2; exit 1; }  # assert
+if [ -n "${DBSYNC_SCHEMA:-""}" ]; then
+  command -v cardano-db-sync > /dev/null 2>&1 || \
+    { echo "The \`cardano-db-sync\` binary not found, line $LINENO" >&2; exit 1; }  # assert
 
   # create clean database
   if [ -z "${DRY_RUN:-""}" ]; then
@@ -138,9 +138,9 @@ EoF
 fi
 
 # enable smash service
-if [ -n "${DBSYNC_REPO:-""}" ] && [ -n "${SMASH:-""}" ]; then
-  [ -e "${DBSYNC_REPO}/smash-server/bin/cardano-smash-server" ] || \
-    { echo "The \`${DBSYNC_REPO}/smash-server/bin/cardano-smash-server\` not found, line $LINENO" >&2; exit 1; }  # assert
+if [ -n "${DBSYNC_SCHEMA:-""}" ] && [ -n "${SMASH:-""}" ]; then
+  command -v cardano-smash-server > /dev/null 2>&1 || \
+    { echo "The \`cardano-smash-server\` binary not found, line $LINENO" >&2; exit 1; }  # assert
 
   cat >> "${STATE_CLUSTER}/supervisor.conf" <<EoF
 [program:smash]
@@ -797,13 +797,13 @@ wait_for_era "Shelley"
 SHELLEY_EPOCH="$(get_epoch)"
 
 # start db-sync
-if [ -n "${DBSYNC_REPO:-""}" ]; then
+if [ -n "${DBSYNC_SCHEMA:-""}" ]; then
   echo "Starting db-sync"
   supervisorctl -s "unix:///${SUPERVISORD_SOCKET_PATH}" start dbsync
 fi
 
 # start smash
-if [ -n "${DBSYNC_REPO:-""}" ] && [ -n "${SMASH:-""}" ]; then
+if [ -n "${DBSYNC_SCHEMA:-""}" ] && [ -n "${SMASH:-""}" ]; then
   echo "Starting smash"
   supervisorctl -s "unix:///${SUPERVISORD_SOCKET_PATH}" start smash
 fi
